spring:
  application:
    name: treinamento-azure
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://meu-primeiro-key-vault.vault.azure.net/

azure:
  storage:
    account-name: ${ACCOUNT_NAME}
    container-name: ${CONTAINER_NAME}
