spring:
  application:
    name: treinamento-azure
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://kv-treinamento-azure.vault.azure.net/

azure:
  storage:
    account-name: ${ACCOUNT_NAME:sttreinamentoazure}
